//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace OpenEphys.MiniscopeV4.Gui
{
    #pragma warning disable // Disable all warnings

    /// <summary>
    /// Miniscope acquisition settings displayed and edited by the GUI.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Miniscope acquisition settings displayed and edited by the GUI.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class MiniscopeSettings
    {
    
        private double _ledBrightness;
    
        private double _focus;
    
        private OpenEphys.Miniscope.GainV4 _sensorGain;
    
        private OpenEphys.Miniscope.FrameRateV4 _frameRate;
    
        private OpenEphys.Miniscope.MiniscopeDaqDigitalIn _ledRespectsDigitalIn;
    
        public MiniscopeSettings()
        {
            _ledBrightness = 0D;
            _focus = 0D;
            _sensorGain = OpenEphys.Miniscope.GainV4.Low;
            _frameRate = OpenEphys.Miniscope.FrameRateV4.Fps30;
            _ledRespectsDigitalIn = OpenEphys.Miniscope.MiniscopeDaqDigitalIn.None;
        }
    
        protected MiniscopeSettings(MiniscopeSettings other)
        {
            _ledBrightness = other._ledBrightness;
            _focus = other._focus;
            _sensorGain = other._sensorGain;
            _frameRate = other._frameRate;
            _ledRespectsDigitalIn = other._ledRespectsDigitalIn;
        }
    
        /// <summary>
        /// The brightness of the excitation LED, as a percentage.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="LedBrightness")]
        [System.ComponentModel.DescriptionAttribute("The brightness of the excitation LED, as a percentage.")]
        public double LedBrightness
        {
            get
            {
                return _ledBrightness;
            }
            set
            {
                _ledBrightness = value;
            }
        }
    
        /// <summary>
        /// The electrowetting lens focus value.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Focus")]
        [System.ComponentModel.DescriptionAttribute("The electrowetting lens focus value.")]
        public double Focus
        {
            get
            {
                return _focus;
            }
            set
            {
                _focus = value;
            }
        }
    
        /// <summary>
        /// The image sensor gain.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="SensorGain")]
        [System.ComponentModel.DescriptionAttribute("The image sensor gain.")]
        public OpenEphys.Miniscope.GainV4 SensorGain
        {
            get
            {
                return _sensorGain;
            }
            set
            {
                _sensorGain = value;
            }
        }
    
        /// <summary>
        /// The image sensor frame rate.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="FrameRate")]
        [System.ComponentModel.DescriptionAttribute("The image sensor frame rate.")]
        public OpenEphys.Miniscope.FrameRateV4 FrameRate
        {
            get
            {
                return _frameRate;
            }
            set
            {
                _frameRate = value;
            }
        }
    
        /// <summary>
        /// The digital input line that gates the excitation LED, if any.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="LedRespectsDigitalIn")]
        [System.ComponentModel.DescriptionAttribute("The digital input line that gates the excitation LED, if any.")]
        public OpenEphys.Miniscope.MiniscopeDaqDigitalIn LedRespectsDigitalIn
        {
            get
            {
                return _ledRespectsDigitalIn;
            }
            set
            {
                _ledRespectsDigitalIn = value;
            }
        }
    
        public System.IObservable<MiniscopeSettings> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new MiniscopeSettings(this)));
        }
    
        public System.IObservable<MiniscopeSettings> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new MiniscopeSettings(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("LedBrightness = " + _ledBrightness + ", ");
            stringBuilder.Append("Focus = " + _focus + ", ");
            stringBuilder.Append("SensorGain = " + _sensorGain + ", ");
            stringBuilder.Append("FrameRate = " + _frameRate + ", ");
            stringBuilder.Append("LedRespectsDigitalIn = " + _ledRespectsDigitalIn);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Commutator connection settings displayed and edited by the GUI.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Commutator connection settings displayed and edited by the GUI.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class CommutatorSettings
    {
    
        private string _portName;
    
        private bool _enable;
    
        private bool _enableLed;
    
        public CommutatorSettings()
        {
            _portName = "";
            _enable = false;
            _enableLed = false;
        }
    
        protected CommutatorSettings(CommutatorSettings other)
        {
            _portName = other._portName;
            _enable = other._enable;
            _enableLed = other._enableLed;
        }
    
        /// <summary>
        /// The name of the serial port the commutator is connected to.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="PortName")]
        [System.ComponentModel.DescriptionAttribute("The name of the serial port the commutator is connected to.")]
        public string PortName
        {
            get
            {
                return _portName;
            }
            set
            {
                _portName = value;
            }
        }
    
        /// <summary>
        /// Whether the commutator motor is enabled.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Enable")]
        [System.ComponentModel.DescriptionAttribute("Whether the commutator motor is enabled.")]
        public bool Enable
        {
            get
            {
                return _enable;
            }
            set
            {
                _enable = value;
            }
        }
    
        /// <summary>
        /// Whether the commutator indication LED is enabled.
        /// </summary>
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="EnableLed")]
        [System.ComponentModel.DescriptionAttribute("Whether the commutator indication LED is enabled.")]
        public bool EnableLed
        {
            get
            {
                return _enableLed;
            }
            set
            {
                _enableLed = value;
            }
        }
    
        public System.IObservable<CommutatorSettings> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new CommutatorSettings(this)));
        }
    
        public System.IObservable<CommutatorSettings> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new CommutatorSettings(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("PortName = " + _portName + ", ");
            stringBuilder.Append("Enable = " + _enable + ", ");
            stringBuilder.Append("EnableLed = " + _enableLed);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Root configuration object persisted to disk and used as the source of truth for the workflow.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Root configuration object persisted to disk and used as the source of truth for t" +
        "he workflow.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    [Bonsai.CombinatorAttribute(MethodName="Generate")]
    public partial class HardwareSettings
    {
    
        private MiniscopeSettings _miniscope;
    
        private CommutatorSettings _commutator;
    
        public HardwareSettings()
        {
        }
    
        protected HardwareSettings(HardwareSettings other)
        {
            _miniscope = other._miniscope;
            _commutator = other._commutator;
        }
    
        /// <summary>
        /// The Miniscope acquisition settings.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Miniscope")]
        [System.ComponentModel.DescriptionAttribute("The Miniscope acquisition settings.")]
        public MiniscopeSettings Miniscope
        {
            get
            {
                return _miniscope;
            }
            set
            {
                _miniscope = value;
            }
        }
    
        /// <summary>
        /// The commutator connection and settings.
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [YamlDotNet.Serialization.YamlMemberAttribute(Alias="Commutator")]
        [System.ComponentModel.DescriptionAttribute("The commutator connection and settings.")]
        public CommutatorSettings Commutator
        {
            get
            {
                return _commutator;
            }
            set
            {
                _commutator = value;
            }
        }
    
        public System.IObservable<HardwareSettings> Generate()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new HardwareSettings(this)));
        }
    
        public System.IObservable<HardwareSettings> Generate<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new HardwareSettings(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("Miniscope = " + _miniscope + ", ");
            stringBuilder.Append("Commutator = " + _commutator);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Serializes a sequence of data model objects into YAML strings.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Serializes a sequence of data model objects into YAML strings.")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [Bonsai.CombinatorAttribute()]
    public partial class SerializeToYaml
    {
    
        private System.IObservable<string> Process<T>(System.IObservable<T> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.SerializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value => serializer.Serialize(value)); 
            });
        }

        public System.IObservable<string> Process(System.IObservable<MiniscopeSettings> source)
        {
            return Process<MiniscopeSettings>(source);
        }

        public System.IObservable<string> Process(System.IObservable<CommutatorSettings> source)
        {
            return Process<CommutatorSettings>(source);
        }

        public System.IObservable<string> Process(System.IObservable<HardwareSettings> source)
        {
            return Process<HardwareSettings>(source);
        }
    }


    /// <summary>
    /// Deserializes a sequence of YAML strings into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.9.0.0 (YamlDotNet v16.0.0.0)")]
    [System.ComponentModel.DescriptionAttribute("Deserializes a sequence of YAML strings into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<MiniscopeSettings>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<CommutatorSettings>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<HardwareSettings>))]
    public partial class DeserializeFromYaml : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public DeserializeFromYaml()
        {
            Type = new Bonsai.Expressions.TypeMapping<HardwareSettings>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(DeserializeFromYaml),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<string> source)
        {
            return System.Reactive.Linq.Observable.Defer(() =>
            {
                var serializer = new YamlDotNet.Serialization.DeserializerBuilder()
                      .WithTypeConverter(new YamlDotNet.Serialization.Converters.DateTimeOffsetConverter())
                      .Build();
                return System.Reactive.Linq.Observable.Select(source, value =>
                {
                    var reader = new System.IO.StringReader(value);
                    var parser = new YamlDotNet.Core.MergingParser(new YamlDotNet.Core.Parser(reader));
                    return serializer.Deserialize<T>(parser);
                });
            });
        }
    }
}