name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build_and_publish:
    uses: open-ephys/github-actions/.github/workflows/build_dotnet_publish_nuget.yml@main
    secrets:
      NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
